### ISSUE TITLE
ПИ21-3

### ISSUE THREAD

**Issue by ManForTen** [VladimirAndropov/fa-cross-practice#1]
ManForTen Петриков

**Comment by mrayuu** [comment]
mrayuu Мерзлова Анастасия

**Comment by AidarFar** [comment]
AidarFar 
Фархутдинов Айдар

**Comment by mrayuu** [comment]
disupova Исупова Дарья

**Comment by anpilove** [comment]
anpilove Анпилов Кирилл

**Comment by DariaKandaurova** [comment]
DariaKandaurova Кандаурова Дарья

**Comment by BogutaO** [comment]
BogutaO Богута Олег

**Comment by Twizdan** [comment]
Twizdan Кусербаев Карим

**Comment by GubanovIV** [comment]
GubanovIV Губанов Иван

**Comment by HoST1er** [comment]
HoST1er Суслов Андрей

**Comment by LuckyGrizzly** [comment]
Lucky Grizzly - Яшинскас Дмитрий

**Comment by Nastianzrv** [comment]
Nastianzrv - Назарова Анастасия

**Comment by mgritta** [comment]
mgritta Кузнецова Маргарита

**Comment by Flyer-DM** [comment]
Flyer-DM Кондрашов Дмитрий

**Comment by Genudza** [comment]
Genudza Мельник Геннадий

**Comment by alexrzntsv** [comment]
alexrzntsv Рязанцев Алексей

**Comment by VladChocolad** [comment]
VladChocolad Коробков Владислав

**Comment by Timidi03** [comment]
Timidi03 Скуратов Артем
