### ISSUE TITLE
ПИ21-4

### ISSUE THREAD

**Issue by basalegend** [VladimirAndropov/fa-cross-practice#5]
basalegend Басалаев

**Comment by ksvfs** [comment]
ksvfs Цыкунов

**Comment by evilyr** [comment]
evilyr Найдёнов Михаил

**Comment by sn1341** [comment]
Смирнов Никита

**Comment by Komandor2003** [comment]
Komandor2003 Лебедев Иван

**Comment by LegendaryTyan** [comment]
LegendaryTyan Орлов Дмитрий

**Comment by Saskeeeeee12** [comment]
Saskeeeeee12 Князев Александр

**Comment by SergeyVetyutnev** [comment]
SergeyVetyutnev Ветютнев

**Comment by fen1ks0059** [comment]
fen1ks0059 Косачев Михаил

**Comment by romaazarubin** [comment]
romaazarubin Зарубин Роман

**Comment by ivtarasovv** [comment]
ivtarasovv Тарасов Иван

**Comment by Krblsyatovo** [comment]
krblsyatovo Рузанов Даниил

**Comment by pedrecho** [comment]
pedrecho
Иванов Дмитрий

**Comment by truefalsemary** [comment]
[truefalsemary](https://github.com/truefalsemary/fa-cross-practice)
Трушкова Мария

**Comment by eln02** [comment]
eln02 Дранникова
